config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  resources :products
  resources :personas

  resources :products do
    get :who_bought, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/persona.rb
require 'date'

class Persona < ApplicationRecord

  validates :nombre,:apellido,:fecha_nac,:dni, presence: true

  validates :nombre, :apellido, format: { with: /\A[a-zA-Z]+\z/, message: "Contiene solo letras" }

  validates :dni, 

  length: {is:8,message: "Dni debe tener 8 númeross"},

  uniqueness: true,

  format: { with: /\A\d+\z/, message: "Contiene solo numeros" } 
 
  
  def age
    dob = fecha_nac
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end



end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: %i[ show edit update destroy ]

  # GET /personas or /personas.json
  def index

    @personas = Persona.all

    @personas_x_mes = @personas.group_by { |t| t.fecha_nac.beginning_of_month}.reverse_each

    totalEdades = 0

    @personas.each do |per|

      totalEdades += per.age

    end 

    @promedio = totalEdades/@personas.length

  end

  # GET /personas/1 or /personas/1.json
  def show

    persona = Persona.find(params[:id])
    @edad = persona.age 

  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas or /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: "Persona was successfully created." }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1 or /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: "Persona was successfully updated." }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1 or /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: "Persona was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def persona_params
      params.require(:persona).permit(:nombre, :apellido, :fecha_nac, :dni)
    end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
<%= form_for(persona) do |f| %>
  <% if persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :apellido %>
    <%= f.text_field :apellido %>
  </div>

  <div class="field">
    <%= f.label :fecha_nac %>
    <%= f.date_select :fecha_nac, start_year: (Date.today.year-100) %>
  </div>

  <div class="field">
    <%= f.label :dni %>
    <%= f.number_field :dni %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form', persona: @persona%>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personas (edad promedio: <%= @promedio %>)</h1>

<table style="border: 1px solid black">
  <thead>
    <tr class="<%= cycle('list_line_odd','list_line_even')%>">
      <td>Nombre</td>
      <td>Apellido</td>
      <td>Fecha nac</td>
      <td>Dni</td>
      <td>Mostrar</td>
      <td>Editar</td>
      <td>Borrar</td>
    </tr>
  </thead>
  <tbody>
    <% cache @personas_x_mes do%>
      <% @personas_x_mes.each do |mes, persons| %>
        <td>Mes: <strong> <%= %w{dummy Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre}[mes.strftime("%m").to_i] %></strong></td>
        <% cache persons do%>
          <% persons.each do |per|%>
            <tr class="entry">
              <td><%= per.nombre %></td>
              <td><%= per.apellido %></td>
              <td><%= per.fecha_nac %></td>
              <td><%= per.dni %></td>
              <td><%= link_to 'Show', per %></td>
              <td><%= link_to 'Edit', edit_persona_path(per) %></td>
              <td><%= link_to 'Destroy', per, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @persona.apellido %>
</p>

<p>
  <strong>Fecha nac:</strong>
  <%= @persona.fecha_nac %>
</p>

<p>
  <strong>Edad</strong>
  <%= @edad %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @persona.dni %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>